module.exports = {
  "moduleData": {
    "id": 17679,
    "name": "hook",
    "cover": "https://img.alicdn.com/tfs/TB1mkjeqlr0gK0jSZFnXXbRRXXa-1404-1292.png",
  },
  "code": {
    "panelDisplay": [
      {
        "panelName": "index.jsx",
        "panelValue": "'use strict';\n\nimport React, { Component } from 'react';\n\nimport styles from './style.js';\n\nclass Page_0 extends Component {\n  render() {\n    return (\n      <div style={styles.box}>\n        <img style={styles.bd} src={'https://img.alicdn.com/tfs/TB1nWPbqi_1gK0jSZFqXXcpaXXa-1404-788.png'} />\n        <span\n          style={styles.main}\n          onClick={e => {\n            console.log('my is text');\n          }}\n        >\n          碎花青春元素悄然走红\n        </span>\n        <span style={styles.submain}>\n          碎花元素可以张扬自我的独特思想品格、风格和生活态度，整体给人感觉一种青春叛逆不羁的自由风格。\n        </span>\n        <div style={styles.ft}>\n          <div style={styles.outer}>\n            <div style={styles.wrap}>\n              <img style={styles.icon} src={'https://img.alicdn.com/tfs/TB1RAjeqlr0gK0jSZFnXXbRRXXa-72-72.png'} />\n              <img style={styles.icon_2} src={'https://img.alicdn.com/tfs/TB1AMYdqbj1gK0jSZFuXXcrHpXa-28-28.png'} />\n            </div>\n            <span style={styles.beautifulClothesFashion}>美衣时尚</span>\n            <div style={styles.tagWrap}>\n              <span style={styles.tag}>时尚媒体</span>\n            </div>\n          </div>\n          <div style={styles.block}>\n            <img style={styles.icon_3} src={'https://img.alicdn.com/tfs/TB1T7YbqeL2gK0jSZFmXXc7iXXa-52-40.png'} />\n            <span style={styles.num}>2980</span>\n          </div>\n        </div>\n      </div>\n    );\n  }\n}\nexport default Page_0;\n",
        "panelType": "js"
      },
      {
        "panelName": "style.js",
        "panelValue": "export default {\n  box: {\n    display: 'flex',\n    alignItems: 'flex-start',\n    flexDirection: 'column',\n    borderRadius: '3.20vw',\n    backgroundColor: '#ffffff',\n    width: '93.60vw',\n    height: '86.13vw'\n  },\n  bd: { width: '93.60vw', height: '52.53vw' },\n  main: {\n    marginTop: '4.00vw',\n    marginLeft: '3.20vw',\n    width: '42.67vw',\n    maxWidth: '88.80vw',\n    height: '4.80vw',\n    overflow: 'hidden',\n    textOverflow: 'ellipsis',\n    lineHeight: '4.80vw',\n    whiteSpace: 'nowrap',\n    color: '#333333',\n    fontSize: '4.27vw',\n    fontWeight: 500\n  },\n  submain: {\n    marginTop: '2.13vw',\n    marginLeft: '3.20vw',\n    width: '90.13vw',\n    height: '10.67vw',\n    overflow: 'hidden',\n    textOverflow: 'ellipsis',\n    lineHeight: '5.33vw',\n    color: '#888888',\n    fontSize: '3.47vw',\n    fontWeight: 300\n  },\n  ft: {\n    boxSizing: 'border-box',\n    display: 'flex',\n    flexDirection: 'row',\n    justifyContent: 'space-between',\n    marginTop: '3.20vw',\n    paddingRight: '3.07vw',\n    paddingLeft: '3.20vw',\n    width: '93.60vw'\n  },\n  outer: { display: 'flex', alignItems: 'center', flexDirection: 'row', height: '4.80vw' },\n  wrap: {\n    display: 'flex',\n    position: 'relative',\n    alignItems: 'flex-start',\n    flexDirection: 'row',\n    justifyContent: 'flex-end',\n    width: '4.80vw',\n    height: '4.80vw'\n  },\n  icon: { position: 'absolute', top: '0.00vw', left: '0.00vw', width: '4.80vw', height: '4.80vw', overflow: 'hidden' },\n  icon_2: { position: 'relative', marginTop: '2.93vw', width: '1.87vw', height: '1.87vw' },\n  beautifulClothesFashion: {\n    marginLeft: '0.80vw',\n    width: '12.80vw',\n    height: '3.73vw',\n    lineHeight: '3.73vw',\n    whiteSpace: 'nowrap',\n    color: '#666666',\n    fontSize: '3.20vw',\n    fontWeight: 300\n  },\n  tagWrap: {\n    boxSizing: 'border-box',\n    display: 'flex',\n    alignItems: 'flex-start',\n    flexDirection: 'row',\n    marginLeft: '0.80vw',\n    borderRadius: '0.80vw',\n    backgroundColor: 'rgba(253,234,238,0.90)',\n    paddingRight: '1.20vw',\n    paddingLeft: '1.07vw',\n    height: '3.73vw'\n  },\n  tag: {\n    marginTop: '0.27vw',\n    width: '10.67vw',\n    height: '3.20vw',\n    lineHeight: '3.20vw',\n    whiteSpace: 'nowrap',\n    color: '#ff2c54',\n    fontSize: '2.67vw',\n    fontWeight: 400\n  },\n  block: { display: 'flex', flexDirection: 'row' },\n  icon_3: { marginTop: '1.47vw', width: '3.47vw', height: '2.67vw' },\n  num: {\n    marginTop: '1.20vw',\n    marginLeft: '0.80vw',\n    width: '6.40vw',\n    height: '3.20vw',\n    lineHeight: '3.20vw',\n    whiteSpace: 'nowrap',\n    color: '#999999',\n    fontSize: '2.67vw',\n    fontWeight: 400\n  }\n};\n",
        "panelType": "js"
      }
    ],
    "noTemplate": true
  }
};
